## Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

## Linear Regression using TF

In [2]:
# Training Data
X_train = np.array([[1.0], [2.0]], dtype=np.float32)           #(size in 1000 square feet)
Y_train = np.array([[300.0], [500.0]], dtype=np.float32)       #(price in 1000s of dollars)

| X_train | Y_train|
|---|---|
|1.0| 300.0|
|2.0| 500.0|

In [3]:
# Set Linear Layer
linear_layer = tf.keras.layers.Dense(units=1, activation = 'linear', )
linear_layer.get_weights()

[]

There are no weights as the weights are not yet instantiated. Let's try the model on one example in X_train. This will trigger the instantiation of the weights. Note, the input to the layer must be 2-D, so we'll reshape it.

In [4]:
X_train[0].reshape(1,1)

array([[1.]], dtype=float32)

In [5]:
a1 = linear_layer(X_train[0].reshape(1,1))
print(a1)

tf.Tensor([[-0.8141527]], shape=(1, 1), dtype=float32)


The result is a tensor (another name for an array) with a shape of (1,1) or one entry.
Now let's look at the weights and bias. These weights are randomly initialized to small numbers and the bias defaults to being initialized to zero.

In [6]:
# Default weights and bias
w, b= linear_layer.get_weights()
print(f"w = {w}, b={b}")

w = [[-0.8141527]], b=[0.]


The weights are initialized to random values so let's set them to some known values.

In [7]:
# Set custom weights
set_w = np.array([[100]])
set_b = np.array([100])

# set_weights takes a list of numpy arrays
linear_layer.set_weights([set_w, set_b])
print(linear_layer.get_weights())

[array([[100.]], dtype=float32), array([100.], dtype=float32)]


In [8]:
# Apply linear_layer function for prediction
a1 = linear_layer(X_train[0].reshape(1,1))
print(a1)

tf.Tensor([[200.]], shape=(1, 1), dtype=float32)


In [9]:
# Make predictions
prediction_tf = linear_layer(X_train)
prediction_tf

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[200.],
       [300.]], dtype=float32)>

## Logistic Regression using TF

In [2]:
# Training Data
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

|X_train|Y_train|
|-------|-------|
|0|0|
|1|0|
|2|0|
|3|1|
|4|1|
|5|1|

In [3]:
pos = Y_train == 1
neg = Y_train == 0
print(pos)
X_train[pos]

[[False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]]


array([3., 4., 5.], dtype=float32)

We can implement a 'logistic neuron' by adding a sigmoid activation. This section will create a Tensorflow Model that contains our logistic layer to demonstrate an alternate method of creating models. Tensorflow is most often used to create multi-layer models. The Sequential model is a convenient means of constructing these models.

In [5]:
# Set logistic layer
model = Sequential(
    [
        tf.keras.layers.Dense(2, input_dim=1,  activation = 'sigmoid', name='L1'),
        tf.keras.layers.Dense(1, input_dim=1,  activation = 'sigmoid', name='L2')
    ]
)
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ L1 (Dense)                      │ (None, 2)              │             4 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ L2 (Dense)                      │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7 (28.00 B)

 Trainable params: 7 (28.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
# View default weights and bias
logistic_layer_1 = model.get_layer('L1')
w,b = logistic_layer_1.get_weights()
print(w,b)
print(w.shape,b.shape)

[[-1.2291319   0.04069805]] [0. 0.]
(1, 2) (2,)


In [8]:
# set weights and bias
set_w = np.array([[2, 1.5]])
set_b = np.array([-4.5, 1.5])

# set_weights takes a list of numpy arrays
logistic_layer_1.set_weights([set_w, set_b])
print(logistic_layer_1.get_weights())

[array([[2. , 1.5]], dtype=float32), array([-4.5,  1.5], dtype=float32)]


In [18]:
print(logistic_layer_2.get_weights())

[array([[-1.0576347 ],
       [-0.41257918]], dtype=float32), array([0.], dtype=float32)]


In [21]:
set_w = np.array([[2], [2]])
set_b = np.array([2])
logistic_layer_2 = model.get_layer('L2')
logistic_layer_2.set_weights([set_w, set_b])
print(logistic_layer_2.get_weights())

[array([[2.],
       [2.]], dtype=float32), array([2.], dtype=float32)]


In [20]:
# Make predictions
a1 = model.predict(X_train)
print(a1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
[[0.97484255]
 [0.9829911 ]
 [0.99127764]
 [0.996425  ]
 [0.9973756 ]
 [0.9975066 ]]
